# Generated by Django 5.0.6 on 2024-10-13 07:22

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikeOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name_Of_liked_user', models.CharField(max_length=200)),
                ('liked_post_id', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='SBUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('dateOfBirthOfUser', models.CharField(max_length=20)),
                ('profileImage', models.ImageField(blank=True, default='', unique=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=50)),
                ('post_up_date', models.DateField(auto_now=True)),
                ('post_txt', models.CharField(max_length=15000)),
                ('user_image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('post_image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('post_slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='generate_slug', unique=True)),
            ],
        ),
    ]
