# Generated by Django 5.0.6 on 2024-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name_Of_liked_user', models.CharField(max_length=200)),
                ('liked_post_id', models.CharField(max_length=100000)),
            ],
        ),
    ]
