# Generated by Django 5.0.6 on 2024-10-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_commentsofuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsofuser',
            old_name='liked_post_id',
            new_name='commented_post_id',
        ),
    ]
