# Generated by Django 5.0.6 on 2024-10-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_liked_post_id_commentsofuser_commented_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsofuser',
            name='comment_txt',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='commentsofuser',
            name='commented_post_id',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='commentsofuser',
            name='user_name_Of_liked_user',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
