# Generated by Django 5.0.6 on 2024-10-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_commentsofuser_comment_txt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_user', models.CharField(blank=True, max_length=200)),
                ('followed_user', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
