# Generated by Django 5.0.6 on 2024-10-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_userfollowdata_flwornot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_from', models.CharField(blank=True, max_length=200)),
                ('message_to', models.CharField(blank=True, max_length=200)),
                ('sent_message', models.TextField()),
                ('sent_date', models.DateField(auto_now=True)),
                ('sno_of_message', models.CharField(blank=True, max_length=2000)),
            ],
        ),
    ]
