# Generated by Django 5.0.6 on 2024-10-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_usermessagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_message_from', models.CharField(blank=True, max_length=200)),
                ('V_message_to', models.CharField(blank=True, max_length=200)),
                ('audio_file', models.FileField(blank=True, default='', unique=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sno_of_message', models.CharField(blank=True, max_length=2000)),
            ],
        ),
    ]
